// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr_P3PLOUQKzWWHBdDkvWp6F6mDubdO1s',
    appId: '1:27332923127:web:7e7e671bb6cd4e737bcdf2',
    messagingSenderId: '27332923127',
    projectId: 'ayts-project',
    authDomain: 'ayts-project.firebaseapp.com',
    storageBucket: 'ayts-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoV-PbKbJz5aDkKxX2aUr9hdUvyXNma9I',
    appId: '1:27332923127:android:aef2c9d97a6116bc7bcdf2',
    messagingSenderId: '27332923127',
    projectId: 'ayts-project',
    storageBucket: 'ayts-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5bR2oP5BX_xv06uqfPb2JGV7E2rjxkM',
    appId: '1:27332923127:ios:e35193143440b7177bcdf2',
    messagingSenderId: '27332923127',
    projectId: 'ayts-project',
    storageBucket: 'ayts-project.appspot.com',
    iosClientId: '27332923127-s130aldod3o9v9rhk16qk17krivpt1nn.apps.googleusercontent.com',
    iosBundleId: 'com.wilywolie.aytsProject',
  );
}
